
num_nodes = 3

Vagrant.configure("2") do |config|
  
  config.vm.box = "lazyfrosch/debian-8-jessie-amd64-puppet"

  # Defining VM properties for each node
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.linked_clone = true if Vagrant::VERSION >= "1.8.0"
    vb.destroy_unused_network_interfaces = true
  end
  
  config.vm.provision "puppet"
  
  1.upto(num_nodes) do |num|
    config.vm.define "node#{num}" do |node|
      node.vm.network :private_network, :ip => "10.100.100.10#{num}"
      node.vm.hostname = "vagrant-node#{num}"
    end
  end
end
